### ISSUE TITLE
Background jobs for storing versions

### ISSUE THREAD

**Issue by krainboltgreene** [paper-trail-gem/paper_trail#1115]
So due to a mistake on my part I brought down my website because paper_trail versions couldn't save. Instead of requiring that versions get saved inside a request, I decided to make them run in the background!

https://gist.github.com/krainboltgreene/7b42135ef2c97977ebea6446f6bf523e

Thoughts?

**Comment by jaredbeck** [comment]
Hi Kurtis. That's an interesting hack. I'm not sure what feedback you're looking for, though. Are you suggesting that PaperTrail should save versions using a background job? Not every application is set up for background jobs. Also, depending on write-frequency, using one job per version insert could lead to a lot of jobs and extra load on the database. Also, background-version-insertion is probably incompatible with [PT-AT](https://github.com/westonganger/paper_trail-association_tracking) because PT-AT expects to insert during the same transaction as the versioned record.

Or, are you suggesting PT should catch more version-creation errors? Some work has been done on that, see 0f90b909. More could be done in that vein, I think.

**Comment by jaredbeck** [comment]
> Well largely I'm looking for a "Holy fuck don't do that you moron" and if not that then I'll gladly write an extension for people to use called paper_trail-background.

It's not clearly a terrible idea :) Worst case scenario, it'll be an interesting experiment.

I think it'd be cool if you used something like the `request_store` gem to keep an in-memory copy of all the version insertions that would have happened and then do those in a batch in the background.

>> Also, background-version-insertion is probably incompatible with PT-AT because PT-AT expects to insert during the same transaction as the versioned record.
> 
> Okay, this is interesting, why does it expect that?

PT-AT uses a `transaction_id` to correlate DML. https://github.com/westonganger/paper_trail-association_tracking/search?q=transaction_id&unscoped_q=transaction_id

**Comment by jaredbeck** [comment]
Closing this, but if you work on this, let's continue to discuss here.

**Comment by krainboltgreene** [comment]
So I found something strange, that I'm betting is accounted for in the sync style:

```
2018-09-24T03:23:11.187Z 92341 TID-ox8b5hwd5 VersionJob JID-cb51093fba1841be253f9df7 INFO: start
2018-09-24T03:23:11.188Z 92341 TID-ox8b5hv9h VersionJob JID-fa18a534857fe2ca569b9343 INFO: start
   (0.7ms)  BEGIN
  ↳ app/jobs/version_job.rb:5
   (0.1ms)  BEGIN
  ↳ app/jobs/version_job.rb:5
  Version Create (25.6ms)  INSERT INTO "versions" ("item_type", "item_id", "event", "whodunnit", "context_id", "object_changes", "created_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["item_type", "Account"], ["item_id", "9d39ca54-027f-4b30-9857-05bdbbf349fb"], ["event", "create"], ["whodunnit", "machine@system.local"], ["context_id", "7620f301-de11-419b-a468-fdb51e4177e3"], ["object_changes", "{\"id\":[null,\"9d39ca54-027f-4b30-9857-05bdbbf349fb\"],\"created_at\":[null,\"2018-09-24 03:23:11 UTC\"],\"updated_at\":[null,\"2018-09-24 03:23:11 UTC\"]}"], ["created_at", "2018-09-24 03:23:11"]]
  ↳ app/jobs/version_job.rb:5
  Version Create (6.4ms)  INSERT INTO "versions" ("item_type", "item_id", "event", "whodunnit", "context_id", "object_changes", "created_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["item_type", "Account"], ["item_id", "9d39ca54-027f-4b30-9857-05bdbbf349fb"], ["event", "create"], ["whodunnit", "machine@system.local"], ["context_id", "7620f301-de11-419b-a468-fdb51e4177e3"], ["object_changes", "{\"id\":[null,\"9d39ca54-027f-4b30-9857-05bdbbf349fb\"],\"created_at\":[null,\"2018-09-24 03:23:11 UTC\"],\"updated_at\":[null,\"2018-09-24 03:23:11 UTC\"]}"], ["created_at", "2018-09-24 03:23:11"]]
  ↳ app/jobs/version_job.rb:5
   (5.8ms)  COMMIT
  ↳ app/jobs/version_job.rb:5
2018-09-24T03:23:11.299Z 92341 TID-ox8b5hv9h VersionJob JID-fa18a534857fe2ca569b9343 INFO: done: 0.111 sec
   (11.6ms)  COMMIT
  ↳ app/jobs/version_job.rb:5
2018-09-24T03:23:11.306Z 92341 TID-ox8b5hwd5 VersionJob JID-cb51093fba1841be253f9df7 INFO: done: 0.119 sec
```

**Comment by krainboltgreene** [comment]
Looks like I'll need to do some sort of uniqueness of jobs based on the version data

**Comment by jaredbeck** [comment]
Just a reminder, if the background approach ends up being too painful, I'm not opposed to adding more `rescue`s and such to PT itself, as we did with https://github.com/paper-trail-gem/paper_trail/commit/0f90b90928b11820ad9238ce44a2b98cde126550

**Comment by krainboltgreene** [comment]
Here's my current implementation, based on version 10:

``` ruby
module PaperTrailRecordTrailBackground
  # @api private
  # @return - The created version object, so that plugins can use it, e.g.
  # paper_trail-association_tracking
  def record_create
    return unless enabled?

    event = PaperTrail::Events::Create.new(@record, true)

    # Merge data from `Event` with data from PT-AT. We no longer use
    # `data_for_create` but PT-AT still does.
    data = event.data.merge(data_for_create)

    trigger_write(@record, data, :create)
  end

  # `recording_order` is "after" or "before". See ModelConfig#on_destroy.
  #
  # @api private
  # @return - The created version object, so that plugins can use it, e.g.
  # paper_trail-association_tracking
  def record_destroy(recording_order)
    return unless enabled?
    return if @record.new_record?

    in_after_callback = recording_order == "after"

    event = PaperTrail::Events::Destroy.new(@record, in_after_callback)

    # Merge data from `Event` with data from PT-AT. We no longer use
    # `data_for_destroy` but PT-AT still does.
    data = event.data.merge(data_for_destroy)

    trigger_write(@record, data, :destroy)
  end

  # @api private
  # @return - The created version object, so that plugins can use it, e.g.
  # paper_trail-association_tracking
  def record_update(force:, in_after_callback:, is_touch:)
    return unless enabled?

    event = PaperTrail::Events::Update.new(@record, in_after_callback, is_touch, nil)

    return unless force || event.changed_notably?

    # Merge data from `Event` with data from PT-AT. We no longer use
    # `data_for_update_columns` but PT-AT still does.
    data = event.data.merge(data_for_update_columns)

    trigger_write(@record, data, :update)
  end

  # @api private
  # @return - The created version object, so that plugins can use it, e.g.
  # paper_trail-association_tracking
  def record_update_columns(changes)
    return unless enabled?

    event = Events::Update.new(@record, false, false, changes)

    return unless force || event.changed_notably?

    # Merge data from `Event` with data from PT-AT. We no longer use
    # `data_for_update_columns` but PT-AT still does.
    data = event.data.merge(data_for_update_columns)

    trigger_write(@record, data, :update)
  end

  private def trigger_write(record, data, event)
    version_class = record.class.paper_trail.version_class
    version_association_name = record.class.versions_association_name
    binding.pry
    version_class.after_transaction do
      VersionJob.perform_async(
        version_class,
        data.merge(
          :"#{version_association_name}_id" => record.id,
          :"#{version_association_name}_type" => record.class.name
        ),
        event
      )
    end
  end
end

PaperTrail::RecordTrail.prepend(PaperTrailRecordTrailBackground)
```

And the job:

``` ruby
class VersionJob < ApplicationJob
  sidekiq_options(:queue => "versions", :unique_across_queues => true, :lock => :until_executed, :log_duplicate_payload => true)

  def perform(version_class, attributes, event)
    version = version_class.constantize.create!(attributes)

    unless event == :create && version.errors.any?
      log_version_errors(version, event)
    end
  end

  def log_version_errors(version, action)
    version.logger&.warn(
      "Unable to create version for #{action} of #{version.item.class.name}" \
        "##{version.item.id}: " + version.errors.full_messages.join(", ")
    )
  end
end

```


Two things to note:

  1. I think there's real room here for a version of `trigger_write`, where the default is sync and explode on failure (aka what we have now).
  2. The background version doesn't need `assign_and_reset_version_association` due to the async nature.

Finally, I've confirmed that record_create is running twice, but not why.

**Comment by krainboltgreene** [comment]
To confirm that it's running twice, I've printed out the event, the data, and the record:

```
==========
record_create called
data: {"event":"create","whodunnit":"machine@system.local","created_at":"2018-10-08T05:03:25.452Z","object_changes":{"id":[null,"d6fb5d24-7562-4f17-a5a6-309cae73520e"],"name":[null,"Diabetic"],"moderation_state":[null,"draft"],"created_at":[null,"2018-10-08T05:03:25.452Z"],"updated_at":[null,"2018-10-08T05:03:25.452Z"]},"transitions":null,"context_id":"7a9cc52b-0e45-45df-b6be-8492cdde8f37","actor_id":null}
record: #<Diet:0x00007ffcae6d68b8>
==========
```

```
==========
record_create called
data: {"event":"create","whodunnit":"machine@system.local","created_at":"2018-10-08T05:03:25.452Z","object_changes":{"id":[null,"d6fb5d24-7562-4f17-a5a6-309cae73520e"],"name":[null,"Diabetic"],"moderation_state":[null,"draft"],"created_at":[null,"2018-10-08T05:03:25.452Z"],"updated_at":[null,"2018-10-08T05:03:25.452Z"]},"transitions":null,"context_id":"7a9cc52b-0e45-45df-b6be-8492cdde8f37","actor_id":null}
record: #<Diet:0x00007ffcae6d68b8>
==========
```

Notice that the *instance of the Diet object itself has the same address*, so it's not some different thread or context. 

The backtraces for both points are identical:

```
lib/source/extensions/paper_trail_record_trail_background.rb:14:in `record_create'
paper_trail-10.0.1/lib/paper_trail/model_config.rb:31:in `block in on_create'
activesupport-5.2.1/lib/active_support/callbacks.rb:426:in `instance_exec'
activesupport-5.2.1/lib/active_support/callbacks.rb:426:in `block in make_lambda'
activesupport-5.2.1/lib/active_support/callbacks.rb:236:in `block in halting_and_conditional'
activesupport-5.2.1/lib/active_support/callbacks.rb:517:in `block in invoke_after'
activesupport-5.2.1/lib/active_support/callbacks.rb:517:in `each'
activesupport-5.2.1/lib/active_support/callbacks.rb:517:in `invoke_after'
activesupport-5.2.1/lib/active_support/callbacks.rb:133:in `run_callbacks'
activesupport-5.2.1/lib/active_support/callbacks.rb:816:in `_run_create_callbacks'
activerecord-5.2.1/lib/active_record/callbacks.rb:346:in `_create_record'
activerecord-5.2.1/lib/active_record/timestamp.rb:102:in `_create_record'
activerecord-5.2.1/lib/active_record/persistence.rb:704:in `create_or_update'
activerecord-5.2.1/lib/active_record/callbacks.rb:342:in `block in create_or_update'
activesupport-5.2.1/lib/active_support/callbacks.rb:132:in `run_callbacks'
activesupport-5.2.1/lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
activerecord-5.2.1/lib/active_record/callbacks.rb:342:in `create_or_update'
activerecord-5.2.1/lib/active_record/persistence.rb:275:in `save'
activerecord-5.2.1/lib/active_record/validations.rb:46:in `save'
activerecord-5.2.1/lib/active_record/transactions.rb:310:in `block (2 levels) in save'
activerecord-5.2.1/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:252:in `transaction'
activerecord-5.2.1/lib/active_record/transactions.rb:212:in `transaction'
activerecord-5.2.1/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
activerecord-5.2.1/lib/active_record/transactions.rb:310:in `block in save'
activerecord-5.2.1/lib/active_record/transactions.rb:325:in `rollback_active_record_state!'
activerecord-5.2.1/lib/active_record/transactions.rb:309:in `save'
activerecord-5.2.1/lib/active_record/suppressor.rb:44:in `save'
activerecord-5.2.1/lib/active_record/persistence.rb:36:in `create'
activerecord-5.2.1/lib/active_record/persistence.rb:33:in `block in create'
activerecord-5.2.1/lib/active_record/persistence.rb:33:in `collect'
activerecord-5.2.1/lib/active_record/persistence.rb:33:in `create'
db/seeds.rb:11:in `block (2 levels) in <main>'
activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `block in transaction'
activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `transaction'
activerecord-5.2.1/lib/active_record/transactions.rb:212:in `transaction'
```

**Comment by krainboltgreene** [comment]
To be clear, here is the entire thing in a console:

```
[2] pry(main)> Diet.create!(name: 'test')
   (0.2ms)  BEGIN
  Diet Exists (0.6ms)  SELECT  1 AS one FROM "diets" WHERE "diets"."name" = $1 LIMIT $2  [["name", "test"], ["LIMIT", 1]]
  Diet Create (3.1ms)  INSERT INTO "diets" ("name", "moderation_state", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["name", "test"], ["moderation_state", "draft"], ["created_at", "2018-10-08 05:11:53.018809"], ["updated_at", "2018-10-08 05:11:53.018809"]]
==========
record_create called
data: {"event":"create","whodunnit":null,"created_at":"2018-10-08T05:11:53.018Z","object_changes":{"id":[null,"b669d13f-c8a6-4cb3-9297-381544323af4"],"name":[null,"test"],"moderation_state":[null,"draft"],"created_at":[null,"2018-10-08T05:11:53.018Z"],"updated_at":[null,"2018-10-08T05:11:53.018Z"]},"transitions":null,"context_id":"4e0fd7c7-f78e-4809-bb88-cbd8550b3992","actor_id":"e5a5b0d1-8304-43de-98ba-3d7841384e0a"}
record: #<Diet:0x00007fe4987d69f8>
==========
==========
record_create called
data: {"event":"create","whodunnit":null,"created_at":"2018-10-08T05:11:53.018Z","object_changes":{"id":[null,"b669d13f-c8a6-4cb3-9297-381544323af4"],"name":[null,"test"],"moderation_state":[null,"draft"],"created_at":[null,"2018-10-08T05:11:53.018Z"],"updated_at":[null,"2018-10-08T05:11:53.018Z"]},"transitions":null,"context_id":"4e0fd7c7-f78e-4809-bb88-cbd8550b3992","actor_id":"e5a5b0d1-8304-43de-98ba-3d7841384e0a"}
record: #<Diet:0x00007fe4987d69f8>
==========
   (1.3ms)  COMMIT
payload is not unique {"class"=>"VersionJob", "args"=>[Version(id: integer, item_type: text, item_id: uuid, event: text, whodunnit: text, actor_id: uuid, context_id: uuid, transitions: jsonb, object_changes: jsonb, created_at: datetime), {:event=>"create", :whodunnit=>nil, :created_at=>Mon, 08 Oct 2018 05:11:53 UTC +00:00, :object_changes=>{"id"=>[nil, "b669d13f-c8a6-4cb3-9297-381544323af4"], "name"=>[nil, "test"], "moderation_state"=>[nil, "draft"], "created_at"=>[nil, Mon, 08 Oct 2018 05:11:53 UTC +00:00], "updated_at"=>[nil, Mon, 08 Oct 2018 05:11:53 UTC +00:00]}, :transitions=>nil, :context_id=>"4e0fd7c7-f78e-4809-bb88-cbd8550b3992", :actor_id=>"e5a5b0d1-8304-43de-98ba-3d7841384e0a", :versions_id=>"b669d13f-c8a6-4cb3-9297-381544323af4", :versions_type=>"Diet"}, :create], "retry"=>true, "queue"=>"versions", "unique_across_queues"=>true, "lock"=>:until_executed, "log_duplicate_payload"=>true, "jid"=>"7c06878cccacbdcb27a56be4", "created_at"=>1538975513.053628, "lock_timeout"=>0, "lock_expiration"=>nil, "unique_prefix"=>"uniquejobs", "unique_args"=>[Version(id: integer, item_type: text, item_id: uuid, event: text, whodunnit: text, actor_id: uuid, context_id: uuid, transitions: jsonb, object_changes: jsonb, created_at: datetime), {:event=>"create", :whodunnit=>nil, :created_at=>Mon, 08 Oct 2018 05:11:53 UTC +00:00, :object_changes=>{"id"=>[nil, "b669d13f-c8a6-4cb3-9297-381544323af4"], "name"=>[nil, "test"], "moderation_state"=>[nil, "draft"], "created_at"=>[nil, Mon, 08 Oct 2018 05:11:53 UTC +00:00], "updated_at"=>[nil, Mon, 08 Oct 2018 05:11:53 UTC +00:00]}, :transitions=>nil, :context_id=>"4e0fd7c7-f78e-4809-bb88-cbd8550b3992", :actor_id=>"e5a5b0d1-8304-43de-98ba-3d7841384e0a", :versions_id=>"b669d13f-c8a6-4cb3-9297-381544323af4", :versions_type=>"Diet"}, :create], "unique_digest"=>"uniquejobs:a846efdd7587f7d4a1f32ddd4a38a8a9"}
=> #<Diet:0x00007fe4987d69f8
 id: "b669d13f-c8a6-4cb3-9297-381544323af4",
 name: "test",
 moderation_state: "draft",
 created_at: Mon, 08 Oct 2018 05:11:53 UTC +00:00,
 updated_at: Mon, 08 Oct 2018 05:11:53 UTC +00:00>
```

**Comment by krainboltgreene** [comment]
Interestingly there are two callbacks defined from papertrail:

```
#<ActiveSupport::Callbacks::Callback:0x00007fb2e93ed1d8
      @chain_config=
       {:scope=>[:kind, :name],
        :terminator=>#<Proc:0x00007fb2e1a72808@/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:603>,
        :skip_after_callbacks_if_terminated=>true},
      @filter=#<Proc:0x00007fb2e93ed430@/Users/krainboltgreene/Code/Poutineer/resources/lib/source/extensions/paper_trail_record_trail_background.rb:9>,
      @if=
       [#<ActiveSupport::Callbacks::Conditionals::Value:0x00007fb2e93ed3e0
         @block=#<Proc:0x00007fb2e93ed390@/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/activemodel-5.2.1/lib/active_model/callbacks.rb:145>>],
      @key=70203197057560,
      @kind=:after,
      @name=:create,
      @unless=[]>
```

```
#<ActiveSupport::Callbacks::Callback:0x00007fb2e1e26260
      @chain_config=
       {:scope=>[:kind, :name],
        :terminator=>#<Proc:0x00007fb2e1a72808@/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:603>,
        :skip_after_callbacks_if_terminated=>true},
      @filter=#<Proc:0x00007fb2e1e264e0@/Users/krainboltgreene/Code/Poutineer/resources/lib/source/extensions/paper_trail_record_trail_background.rb:9>,
      @if=
       [#<ActiveSupport::Callbacks::Conditionals::Value:0x00007fb2e1e26490
         @block=#<Proc:0x00007fb2e1e26440@/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/activemodel-5.2.1/lib/active_model/callbacks.rb:145>>],
      @key=70203135308400,
      @kind=:after,
      @name=:create,
      @unless=[]>
```

**Comment by krainboltgreene** [comment]
@jaredbeck 	Okay, I figured it out. Turns out I assumed multiple has_paper_trail calls would "merge" (I have multiple concerns with different levels of papertrails), but it looks like it's additive in the case of callbacks.

**Comment by jaredbeck** [comment]
> Turns out I assumed multiple has_paper_trail calls would "merge" (I have multiple concerns with different levels of papertrails), but it looks like it's additive in the case of callbacks.

The behavior in this scenario is undefined. Every time you call `has_paper_trail`, it attempts to install callbacks. I don't know how rails handles multiple callbacks with the same name, but if you say that multiple callbacks are installed, I would not be surprised.

> I think there's real room here for a version of trigger_write, where the default is sync and explode on failure (aka what we have now).

Instead of overwriting a function, what do you think of the adapter pattern. I was very happy with how [`object_changes_adapter`](https://github.com/paper-trail-gem/paper_trail#6c-custom-object-changes) turned out. Please take a look at that and tell me if you think something similar would work for you here.

**Comment by krainboltgreene** [comment]
Yes, I think that is a good idea. I'll begin the PR tonight.

**Comment by jaredbeck** [comment]
I'm going to close this issue, Kurtis, and I'll look for your PR. Thanks!

**Comment by krainboltgreene** [comment]
Tada: https://github.com/krainboltgreene/paper_trail-background.rb https://rubygems.org/gems/paper_trail-background

**Comment by jaredbeck** [comment]
Cool! If you want to put something in the PT readme about this, section 8. "Plugins" would be appropriate. https://github.com/paper-trail-gem/paper_trail#8-papertrail-plugins
