### ISSUE TITLE
Association tracking bug

### ISSUE THREAD

**Issue by seanlinsley** [paper-trail-gem/paper_trail#1134]
When using 6c34a3dd5a5f8c1b042f458b7727c9d3bbf81a50 in my application, I'm running into this error:

```
   4: from bundler/gems/paper_trail-6c34a3dd5a5f/lib/paper_trail.rb:147:in `<main>'
   3: from gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
   2: from gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'
   1: from gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `block in require'
gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': 
cannot load such file -- paper_trail-association_tracking (LoadError)
```

**Comment by seanlinsley** [comment]
We're not using association tracking. It appears to be a bug introduced by db9c392d2f685e0dde970bf2e8b15b7eb3178f0e

**Comment by jaredbeck** [comment]
doh. I forgot to remove the `require` on `lib/paper_trail.rb:147`
